export const labels = {
  es: {
    today: "Hoy",
    week: "Semana",
    month: "Mes",
    search: "Buscar",
    tasks: "Tareas",
    focus: "Enfoque",
    events: "Eventos",
    history: "Historial",
    statistics: "Estadísticas",
    reminders: "Recordatorios",
    schedules: "Horarios",
    categories: "Categorías",
    templates: "Plantillas",
    settings: "Ajustes",
    data: "Datos",
    more: "Más",
    demo: "Modo demo",
    demoHint: "Datos privados de prueba · se restablecen en 24 h",
    reset: "Restablecer demo",
    create: "Crear mi cuenta",
    addTask: "Añadir tarea",
    addEvent: "Añadir evento",
    addSchedule: "Añadir horario",
    addCategory: "Añadir categoría",
    title: "Título",
    name: "Nombre",
    date: "Fecha",
    empty: "No hay elementos todavía",
    completed: "Completada",
    mark: "Marcar como completada",
    active: "Activo",
    isolated:
      "Esta demo funciona solo en tu navegador y nunca modifica cuentas reales.",
    protected:
      "Las acciones de cuenta y cualquier operación destructiva real están desactivadas.",
    morning: "Mañana",
    afternoon: "Tarde",
    night: "Noche",
    anytime: "En cualquier momento",
    progress: "Progreso de hoy",
    sample: "Explora, añade, completa y elimina elementos libremente.",
    focusIntro: "Prueba una sesión guiada vinculada a una tarea.",
    start: "Iniciar",
    pause: "Pausar",
    resume: "Continuar",
    resetTimer: "Reiniciar",
    focusTime: "Enfoque profundo",
    breakTime: "Descanso",
    selectTask: "Tarea vinculada",
    searchPlaceholder: "Buscar tareas y eventos",
    noResults: "No hay resultados para esta búsqueda.",
    thisMonth: "Vista general del mes",
    completedSessions: "Sesiones completadas",
    focusedMinutes: "Minutos de enfoque",
    completionRate: "Tareas completadas",
    reminderHint:
      "Los recordatorios de la demo no envían notificaciones reales.",
    enabled: "Activado",
    disabled: "Desactivado",
    useTemplate: "Usar plantilla",
    templateAdded: "Plantilla añadida a tus tareas",
    dataHint: "Tus cambios de la demo se guardan solo en este navegador.",
    exportDemo: "Descargar datos de la demo",
    exploreMore: "Explora todas las herramientas de Planora",
    skip: "Saltar al contenido",
    delete: "Eliminar",
    use: "Usar",
  },
  en: {
    today: "Today",
    week: "Week",
    month: "Month",
    search: "Search",
    tasks: "Tasks",
    focus: "Focus",
    events: "Events",
    history: "History",
    statistics: "Statistics",
    reminders: "Reminders",
    schedules: "Schedules",
    categories: "Categories",
    templates: "Templates",
    settings: "Settings",
    data: "Data",
    more: "More",
    demo: "Demo mode",
    demoHint: "Private sample data · resets in 24 hours",
    reset: "Reset demo",
    create: "Create my account",
    addTask: "Add task",
    addEvent: "Add event",
    addSchedule: "Add schedule",
    addCategory: "Add category",
    title: "Title",
    name: "Name",
    date: "Date",
    empty: "Nothing here yet",
    completed: "Completed",
    mark: "Mark as complete",
    active: "Active",
    isolated:
      "This demo runs only in your browser and never changes real accounts.",
    protected:
      "Account actions and every real destructive operation are disabled.",
    morning: "Morning",
    afternoon: "Afternoon",
    night: "Night",
    anytime: "Anytime",
    progress: "Today's progress",
    sample: "Explore, add, complete and remove items freely.",
    focusIntro: "Try a guided session linked to a task.",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    resetTimer: "Reset",
    focusTime: "Deep focus",
    breakTime: "Break",
    selectTask: "Linked task",
    searchPlaceholder: "Search tasks and events",
    noResults: "No results for this search.",
    thisMonth: "Month overview",
    completedSessions: "Completed sessions",
    focusedMinutes: "Focus minutes",
    completionRate: "Tasks completed",
    reminderHint: "Demo reminders never send real notifications.",
    enabled: "Enabled",
    disabled: "Disabled",
    useTemplate: "Use template",
    templateAdded: "Template added to your tasks",
    dataHint: "Demo changes are stored only in this browser.",
    exportDemo: "Download demo data",
    exploreMore: "Explore every Planora tool",
    skip: "Skip to content",
    delete: "Delete",
    use: "Use",
  },
} as const;

export type DemoCopy = (typeof labels)["es"] | (typeof labels)["en"];
