"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { taskSchema } from "@/lib/validation/task";
import { z } from "zod";
const scheduleSchema=z.object({name:z.string().trim().min(1).max(80),description:z.string().max(500).optional(),emoji:z.string().max(16).optional()});
const categorySchema=z.object({name:z.string().trim().min(1).max(60),colour:z.string().regex(/^#[0-9A-Fa-f]{6}$/),emoji:z.string().max(16).optional()});
async function auth(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Unauthorized");return{db,user}}
export async function createSchedule(input:unknown){const value=scheduleSchema.parse(input),{db,user}=await auth();const {data,error}=await db.from("schedules").insert({...value,user_id:user.id}).select("id").single();if(error)throw new Error("Unable to save schedule");const {data:p}=await db.from("profiles").select("active_schedule_id").eq("id",user.id).single();if(!p?.active_schedule_id)await db.from("profiles").update({active_schedule_id:data.id}).eq("id",user.id);revalidatePath("/","layout");return data}
export async function createCategory(input:unknown){const value=categorySchema.parse(input),{db,user}=await auth();const {error}=await db.from("categories").insert({...value,user_id:user.id});if(error)throw new Error("Unable to save category");revalidatePath("/","layout")}
export async function createTask(input:unknown){const value=taskSchema.parse(input),{db,user}=await auth();const r=value.recurrence,t=value.timing;const {error}=await db.from("tasks").insert({user_id:user.id,schedule_id:value.scheduleId,category_id:value.categoryId??null,title:value.title,description:value.description??null,emoji:value.emoji??null,task_kind:r.type==="once"?"one_time":"habit",recurrence_type:r.type,recurrence_config:r,time_mode:t.mode,day_part:t.mode==="day_part"?t.dayPart:null,start_time:t.mode==="specific_time"||t.mode==="time_range"?t.startTime:null,end_time:t.mode==="time_range"?t.endTime:null,start_date:value.startDate,end_date:value.endDate??null});if(error)throw new Error("Unable to save task");revalidatePath("/","layout")}
export async function toggleCompletion(taskId:string,occurrenceDate:string,snapshot:Record<string,string|null>){const id=z.string().uuid().parse(taskId),day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(occurrenceDate),{db,user}=await auth();const {data}=await db.from("task_completions").select("id").eq("task_id",id).eq("occurrence_date",day).maybeSingle();const result=data?await db.from("task_completions").delete().eq("id",data.id):await db.from("task_completions").insert({user_id:user.id,task_id:id,occurrence_date:day,task_snapshot:snapshot});if(result.error)throw new Error("Unable to update completion");revalidatePath("/","layout");return{completed:!data}}
export async function signOut(){const {db}=await auth();await db.auth.signOut()}
